name: Linux test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GTEST: googletest-release-1.8.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: sudo apt-get install unzip
      
    - name: Prepare gtest
      run: unzip ${{env.GTEST}}.zip
      
    - name: Make Google Test in './build/gtest/' folder
      run: |
        mkdir build && cd build
        mkdir gtest && cd gtest
        cmake ../../${{env.GTEST}} && make

    - name: Build target and unit-test
      run: cd ${{github.workspace}}/build && cmake ../ && make

    - name: Test
      run: cd ${{github.workspace}}/build && ./unit_test
      
